config/routes.rb
Fixit::Application.routes.draw do

  resources :requests
  match "request/search" => "requests#search", :as => "search"
  match "request/do_search" => "requests#do_search"
  match "requests/send_status_email/:id" => "requests#send_status_email"
  match "buildings/get_info/:name" => "buildings#get_info"
  match "zones/get_info/:name" => "zones#get_info"
  root :to => redirect('/requests')
  match "/logout" => "application#logout", :as => "logout"
  match '/active' => 'application#active'
  match '/timeout' => 'application#timeout'
  match "/work_order/" => "requests#screpe"

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :name, :phone, :email, :location_id, :status, :tag_number, :description, :reject_reason, :location_description, :item_description, :accept_date, :reject_date, :created_at, :updated_at, :area_id, :request_number, :user, :area

  belongs_to :user, :foreign_key => "user_id"
  belongs_to :area, :foreign_key => "area_id"
  has_one :building, :through => :area
  has_one :zone, :through => :building

  validates_presence_of :area, :message => "Choose a Location"
  validates_presence_of :name, :message => "Enter a name"
  validates_presence_of :description, :message => "Enter a description"
  validates_format_of :phone, :with => /^[\(\)0-9\- \+\.]{10,20}$/, :message => "Enter a phone number"
  validates_format_of :email, :with => /^[a-zA-Z0-9._-]+@berkeley.edu$/, :message => "Enter a Berkeley email address"

  def to_list
    toReturn =  ["Name: #{name}", "Phone Number: #{phone}", "Email: #{email}", "Zone: #{zone}", "Building: #{building}", "Area: #{area}", "Description: #{description}"]
    return toReturn
  end

end

app/controllers/requests_controller.rb
require 'open-uri'

class RequestsController < ApplicationController
  def index
  end

  def create
    uid = session[:cas_user]

    user = User.find_by_uid(uid)
    if user.nil?
      user = User.create!(:uid => uid)
    end

    request_hash = params[:request]
    area = Area.find_by_name(request_hash[:area])
    @email = request_hash[:email]
    email = @email
    @description = request_hash[:description]

    if email =~ /^[a-zA-Z0-9._-]+$/
      email += "@berkeley.edu"
    end

    @request = Request.new(:name => request_hash[:name], :phone => request_hash[:phone], :email => email, :description => request_hash[:description], :area => area, :user => user)

    @request.status = 'pending'
    if @request.save
      # send an email containing the maintenance request information

      email_body = ["#{@request.name} has submitted the following maitenance request:", ""]
      @request.to_list.each do |x|
        email_body << x
      end
      email_body << ""
      email_body << "Please input this into the database and send any correspondance to #{@request.email}. Thank you for your time."
      subject_text = "[Maintenance Request Submitted] #{@request.name} from #{@request.area}"

      UserMailer.request_created_email(email_body, subject_text).deliver!
      flash[:notice] = "Request submitted"
      redirect_to request_path(@request.id)
    else
      setup_areas
      render 'new'
    end

  end

  def show
    id = params[:id]
    @request = Request.find_by_id(id)
    if(@request.nil?)
      flash[:notice] = "There is no request with the specified id: " + id
      redirect_to requests_path
      return
    end
  end


  def decodeLocationId(locationId) #returns the corresponding area
        @building_decoder = {
      "U1C"=>"Central 1",
      "CB"=>"Channing Bowditch",
      "CB-GRD"=>"Channing Bowditch Ground",
      "CH"=>"Cheney Hall",
      "CN"=>"Christian Hall",
      "DE"=>"Deutsch Hall",
      "FB"=>"Freeborn Hall",
      "JH"=>"Ida Jackson House",
      "PU"=>"Putnam Hall",
      "SL"=>"Slottman Hall",
      "U1-ALL"=>"Unit 1 All Buildings",
      "U1-GRD"=>"Unit 1 Ground",
      "U2C"=>"Central 2",
      "CU"=>"Cunningham Hall",
      "DA"=>"Davidson Hall",
      "EH"=>"Ehman Hall",
      "GR"=>"Griffiths Hall",
      "TO"=>"Towle Hall",
      "U2-ALL"=>"Unit 2 All Buildings",
      "U2-GRD"=>"Unit 2 Ground",
      "WA"=>"Wada Hall",
      "MC"=>"Martinez Commons",
      "BC-GRD"=>"Beverly Cleary Ground",
      "BC"=>"Beverly Cleary Hall",
      "U3C"=>"Central 3",
      "IS"=>"Ida Sproul Hall",
      "MV-GRD"=>"Manville Ground",
      "MV"=>"Manville Hall",
      "NO"=>"Norton Hall",
      "PR"=>"Priestley Hall",
      "SB"=>"Spens Black Hall",
      "U3-ALL"=>"Unit 3 All Buildings",
      "U3-GRD"=>"Unit 3 Ground",
      "BO-GRD"=>"Bowles Ground",
      "BO"=>"Bowles Hall",
      "FH1"=>"FH Building 1",
      "FH2"=>"FH Building 2",
      "FH3"=>"FH Building 3",
      "FH4"=>"FH Building 4",
      "FH5"=>"FH Building 5",
      "FH6"=>"FH Building 6",
      "FH7"=>"FH Building 7",
      "FH8"=>"FH Building 8",
      "FH9"=>"FH Building 9",
      "FH-ALL"=>"Foothill All Buildings",
      "FH-GRD"=>"Foothill Ground",
      "ST-GRD"=>"Stern Ground",
      "ST"=>"Stern Hall",
      "CK1"=>"CK Building 1",
      "CK2"=>"CK Building 2",
      "CK3"=>"CK Building 3",
      "CK4"=>"CK Building 4",
      "CK6"=>"CK Building 6",
      "CK7"=>"CK Building 7",
      "CK8"=>"CK Building 8",
      "CK9"=>"CK Building 9",
      "CK11"=>"CK Building 11",
      "CK12"=>"CK Building 12",
      "CK13"=>"CK Building 13",
      "CK16"=>"CK Building 16",
      "CK17"=>"CK Building 17",
      "CK18"=>"CK Building 18",
      "CK19"=>"CK Building 19",
      "CK20"=>"CK Building 20",
      "CK-ALL"=>"Clark Kerr Campus All Buildings",
      "CK-GRD"=>"Clark Kerr Ground"}
    if( not locationId.index("-"))
      return nil
    end
    building_code = locationId[0..locationId.rindex("-")-1]
    area_code = locationId[locationId.rindex("-")+1..-1]
    puts building_code
    building = Building.find_by_name(@building_decoder[building_code])

    if(building)
      area = Area.find(:first, :conditions =>
                       ["name LIKE ? AND building_id = ?",
                        "#{area_code}%", building.id])
      return area
    end
    return nil
  end


  def screpe
    @work_order_id = params[:request_id][:request_id]
    page = Nokogiri::HTML(open(generate_work_order_uri(@work_order_id)))
    if(/No information/ =~ page.css('td')[0].text.strip)
      flash[:warning] = "There is no work order with the id: " + @work_order_id + ". Are you sure you formatted the ID correctly? (e.g. HM-654321)"
      redirect_to search_path and return
    end
    @building_name = screpe_helper(page, 9, 1)
    @location_id = screpe_helper(page, 10, 1)
    @request_date = screpe_helper(page, 12, 1)
    @date_closed = screpe_helper(page, 15, 1)
    @requested_action = screpe_helper(page, 19, 1)
    @corrective_action = screpe_helper(page, 20, 1)
    @completed_notice = screpe_helper(page, 22, 0)
    area = decodeLocationId(@location_id)
    puts area
    if(area)
      @location_id = area.name
    end

    if(@completed_notice == "")
      @completed_notice = "Working on it"
    end
  end

  def screpe_helper(page, tr, td)
    table_rows = page.css("tr")
    if(table_rows) #one big null check
      table_row = table_rows[tr]
      if (table_row)
        table_data = table_row.css("td")
        if(table_data)
          table_datum = table_data[td]
          if(table_datum)
            return table_datum.text.strip()
          end
        end
      end
    end
    return ""
  end



  #This can be stubed out in test so that we do not make web requests during tests
  def generate_work_order_uri(id)
    return 'https://maintenance.housing.berkeley.edu/query_wo_results.html?' + id
  end

  def search
    @sent_email = params[:sent_email]
    uid = session[:cas_user]
    user = User.find_by_uid(uid)
    @requests = nil
    @requests = user.requests unless user.nil?
    @requests = [] if @requests.nil?
    @headers = ["Request to See Status", "Location", "Date", "Description"]
  end

  def do_search
    redirect_to "/requests/#{params[:search]['request_id']}"
  end

  def new
    setup_areas
    @request = Request.new
    @email = nil
    @description = nil
  end

  def setup_areas_again

  end

  def setup_areas
    @zones = ['Choose a Zone']
    Zone.all.each do |zone|
      @zones << zone.name
    end
    @buildings = ['Choose a Building']
    Building.all.each do |building|
      @buildings << building.name
    end
    @areas = ['Choose a Building First']
    Area.all.each do |area|
      @areas << area.name
    end

  end

  def send_status_email
    id = params[:id]
    @request = Request.find_by_id(id)
    email_body = ["#{@request.name} would like to see the status of the following request:", ""]
    @request.to_list.each do |x|
      email_body << x
    end
    email_body << ""
    email_body << "Please send your response to #{@request.email}. Thank you."
    subject_text = "[View Maintenance Request Status] #{@request.name} from #{@request.area}"

    UserMailer.request_view_status_email(email_body, subject_text).deliver!
    flash[:notice] = "Your status request was received. You should receive an update email from an RSSP staff member shortly."
    redirect_to :controller => :requests, :action => :search, :sent_email => id
  end

end

app/views/requests/_areas.html.haml
= select :request, :area, @areas

app/views/requests/_buildings.html.haml
= select :request, :building, @buildings

app/views/requests/index.html.haml
.centered_button_holder
  %div
    %div{:class => "media", :style => "height:220px"}
      %a{:class => "pull-left submit_maintenance_button media-object", :href => "/requests/new", :id => 'submit_request'}
      %div{:class => "media-body media-top"}
        %h4{:class => "media-heading"}
          =link_to "Submit Request", new_request_path()
        Is something broken in the Residence Halls? Let us know
        

    %div{:class => "media", :style => "height:220px"}
      %a{:class => "pull-left media-object check_status_button", :href => "/request/search", :id => 'check_status'}
      %div{:class => "media-body"}
        %h4{:class => "media-heading"}
          =link_to "Check Status", search_path()
        Need to know how your request is coming along? Check it out here






-#= button_to 'Check Status', search_path(), :class => "front_page_button"
-#= button_to 'Submit', new_request_path, :class => "front_page_button", :method => :get, :id => 'submit_request'

app/views/requests/new.html.haml
- unless @request.errors.empty?
  #warning
    %ul
      - @request.errors.messages.each do |error|
        %li= error[1][0]

%h1 Submit a Request

= form_tag requests_path, :id => "Submit a Request" do 
  
  = label :request, :zone, 'Zone'
  = select :request, :zone, @zones
  
  = label :request, :building, 'Building'
  = render :partial => 'buildings'

  = label :request, :area, 'Area'
  = render :partial => 'areas'

  = label :request, :name, 'Name'
  = text_field :request, 'name'

  = label :request, :phone, 'Phone Number'
  = text_field :request, 'phone'

  = label :request, :email, 'Email'
  %div{:class => ["input-append"]}
    %input{:class => "span2", :id => "request_email", :name => "request[email]", :type => "text", :value => "#{@email}" }
      %span{:class=>"add-on"}
        @berkeley.edu

  = label :request, :description, 'Request Description'
  -#  = text_area :request, 'description', :cols=>"20", :rows => "3"

  <div><textarea id="request_description" name="request[description]" data-provide="limit" data-counter="#counter" maxChars="250">
  =@description
  </textarea></div>
  <em id="counter"></em>
  %br
  = submit_tag "Submit", :id=>"submit"

%br
.centered_button_holder
= button_to "Back to Home", '/requests', :class => "front_page_button", :method => :get, :id => "home"

%div{:id=>"new_page", :display=>"none"}

app/views/requests/screpe.html.haml
%h1 Work Order: #{@work_order_id}

%ul
 %li
  Building:
  = @building_name
 %li
  Location:
  = @location_id
 %li
  Description:
  = @requested_action
 %li
  Corrective Action:
  = @corrective_action
 %li
  Current Status: 
  = @completed_notice
 %li
  Date Requested:
  =@request_date
 -if @date_closed != ""
  %li
   Date Closed:
   =@date_closed
= button_to "Back to Home", '/requests', :class => "front_page_button", :method => :get, :id=>"home"

app/views/requests/search.html.haml
%h3 Find a Work Order by ID

= form_tag "/work_order/", :id => "Search", :class => "input-append" do 
  
  %br
  = text_field :request_id, 'request_id', :class => "span2", :placeholder => "(e.g. HM-654321)"
  = submit_tag "Search", :class => "btn"
%h7 (Don't know your Work Order number? Find your request below)

%br
%br
%h3 My Requests
%table{:class => "table table-hover"}
  %thead
    %tr
      - @headers.each do |header|
        %td
          %b= header
  %tbody
    - @requests.each do |request|
      %tr
        %td 
          - if (request.id.to_s == @sent_email.to_s)            
            Submit
          - else
            = link_to "Submit", "/requests/send_status_email/#{request.id}"
        %td= request.area
        %td= request.created_at.strftime("%b %d, %Y")
        %td= request.description
         
= button_to "Back to Home", '/requests', :class => "front_page_button", :method => :get, :id=>"home"

app/views/requests/show.html.haml
%h1 Your Request

%ul
 %li
  Description:
  = @request.description
 %li
  Location:
  = @request.area.name
 %li
  Current Status: 
  = @request.status
 %li
  Building:
  = @request.area.building.name
 %li
  Zone:
  = @request.area.building.zone.name
 %li
  Date Requested:
  =@request.created_at
 %li
  Work Request Id:
  = @request.id


= button_to "Back to Home", '/requests', :class => "front_page_button", :method => :get, :id=>"home"