config/routes.rb
Fixit::Application.routes.draw do

  resources :requests
  match "request/search" => "requests#search", :as => "search"
  match "request/do_search" => "requests#do_search"
  match "requests/send_status_email/:id" => "requests#send_status_email"
  match "buildings/get_info/:name" => "buildings#get_info"
  match "zones/get_info/:name" => "zones#get_info"
  root :to => redirect('/requests')
  match "/logout" => "application#logout", :as => "logout"
  match '/active' => 'application#active'
  match '/timeout' => 'application#timeout'
  match "/work_order/" => "requests#screpe"

end

app/views/layouts/.#index.html.haml
saasbook@saasbook.2824:1349559644

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "UCB Fixit"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          #ucb_icon_div
            -#= image_tag '/images/ucb_icon.png', :id => 'ucb_icon'
          #header_text_div
            %h2.title{:id => 'header_text'}=link_to "UC Berkeley Maintenance", requests_path()
          = link_to 'CalNet Logout', logout_path()
    #main{:role => "main"}
      .container
        .content
          .row
            - if flash[:notice]
              #notice.message= flash[:notice]
            - elsif flash[:warning]
              #warning.message= flash[:warning]
            = yield
          %footer

app/views/layouts/index.html.haml
-# This file is app/view/layouts/index.html.haml
%h1 Test